apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahey-server
  namespace: ahey-chat
  labels:
    app: ahey-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahey-server
  template:
    metadata:
      labels:
        app: ahey-server
    spec:
      containers:
        - name: ahey-server
          image: 192.168.1.11:5000/ahey_chat-server:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ahey-server-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
