apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-scraper-refresh
  namespace: data-scraper
  labels:
    app: data-scraper-refresh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-scraper-refresh
  template:
    metadata:
      labels:
        app: data-scraper-refresh
    spec:
      containers:
        - name: data-scraper-refresh
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:2dc60a0
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: METHOD
              value: refreshCompanies
            - name: ORDER
              value: asc
            - name: LIMIT
              value: "500"
          envFrom:
            - secretRef:
                name: data-scraper-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: ghcr-login-secret
---

