apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infotropyiq
resources:
  - namespace.yaml
  # - deployment-us.yaml
  # - deployment-gb.yaml
  # - deployment-refresh.yaml
  # - deployment-job-scraping.yaml
  # - deployment-apollo.yaml
  # - deployment-copy-by-industry.yaml
  # - deployment-copy-indprd.yaml
