apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infotropyiq
resources:
  - namespace.yaml
  - deployment-us.yaml
  - deployment-refresh.yaml
  - deployment-job-scraping.yaml
  - deployment-apollo.yaml
