apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahey-automation
  namespace: ahey-automation
  labels:
    app: ahey-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahey-automation
  template:
    metadata:
      labels:
        app: ahey-automation
    spec:
      containers:
        - name: ahey-automation
          image: 192.168.1.11:5000/ahey_chat-automation:latest
          imagePullPolicy: IfNotPresent # Important for using remote images
          envFrom:
            - secretRef:
                name: ahey-automation-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
