apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://infotropyiq-stg.vault.azure.net
      tenantId: 17c72efa-3dbb-47ab-9e34-56dcd4929dca
      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets
