apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meilisearch

resources:
  - namespace.yaml
  - secret.yaml # or secret-sealed.yaml if using Sealed Secrets
  - repository.yaml
  - release.yaml
