apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.80-192.168.1.90 # ğŸ“ Customize to your local network
