apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.0.80-172.18.0.90 # ğŸ“ Customize to your local network
