---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: infotropyiq-server
  namespace: infotropyiq
  labels:
    app: infotropyiq-server
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: infotropyiq-server
  template:
    metadata:
      labels:
        app: infotropyiq-server
    spec:
      containers:
        - name: infotropyiq-server
          image: 192.168.1.11:5000/infotropyiq-server:latest
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: infotropyiq-env
          env:
            - name: BETTER_AUTH_URL
              value: "http://localhost:3000"
            - name: NODE_ENV
              value: "production"
            - name: POLAR_SUCCESS_URL
              value: "http://infotropyiq-web:80/success?checkout_id={CHECKOUT_ID}"
            - name: CORS_ORIGIN
              value: "http://infotropyiq-web:80"
          ports:
            - containerPort: 3000