---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: infotropyiq-server
  namespace: infotropyiq
  labels:
    app: infotropyiq-server
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: infotropyiq-server
  template:
    metadata:
      labels:
        app: infotropyiq-server
    spec:
      containers:
        - name: infotropyiq-server
          image: 192.168.1.11:5000/infotropyiq-server:latest
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: infotropyiq-env
          env:
            - name: BETTER_AUTH_URL
              value: "https://stg-app.infotropyiq.com"
            - name: NODE_ENV
              value: "production"
            - name: POLAR_SUCCESS_URL
              value: "https://stg-app.infotropyiq.com/success?checkout_id={CHECKOUT_ID}"
            - name: CORS_ORIGIN
              value: "https://stg-app.infotropyiq.com"
            - name: MEILISEARCH_HOST
              value: "http://meilisearch.meilisearch.svc.cluster.local:7700"
            - name: USE_MEILISEARCH
              value: "true"
            - name: JOB_SPY_API
              value: "http://jobspy-api.jobspy.svc.cluster.local:8000"
          ports:
            - containerPort: 3000
